import Head from "next/head";
import Image from "next/image";
import Home from "../src/Components/Home/Home";
import styles from "../styles/Home.module.css";

export default function HomePage() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        
        
      </Head>
      <div className={styles.mainHead}>Weather App (Search By City!)</div>
      <Home />
    </div>
  );
}
